### ISSUE TITLE
Parâmetros hexadecimais na diretiva ORG são tratados como 0

### ISSUE THREAD

**Issue by phckopper** [petcomputacaoufrgs/hidracpp#15]
Quando utilizada a diretiva `ORG` com um parâmetro iniciado com "H" ou "h", ao invés de ser interpretado como hexadecimal o parâmetro é tratado como 0.

Versão: Hidra v1.1.0 (Jul  6 2020)

Exemplo:

![Screenshot_20210224_170019](https://user-images.githubusercontent.com/4000637/109059058-8a3e3e00-76c2-11eb-9493-5cca882aab50.png)

**Comment by viniciuscarra** [comment]
Criei um branch (fix/org-with-hex) e já está com uma possível solução. Acho que cabe algum polimento, mas a princípio está funcionando.

**Comment by phckopper** [comment]
Boa, Vini! Vou usar tua versão e reporto se tiver qualquer problema, valeu!

**Comment by felipeal** [comment]
Oi, pode manter aberta até entrar a solução!

@viniciuscarra sugiro reusar `stringToInt` no fix
