### ISSUE TITLE
Configurações do projeto: proteção de branches

### ISSUE THREAD

**Issue by felipeal** [petcomputacaoufrgs/hidracpp#17]
Na última vez que abri um Pull Request, vi que não temos a exigência de N revisores para dar merge em PRs para a master. O merge fica liberado como mostra a imagem.

  ![image](https://user-images.githubusercontent.com/8339493/110250020-f38e3e80-7f57-11eb-91cd-97c56fbf7b07.png)

Seria possível adicionar essa restrição? Talvez com mínimo de **2 revisores**, e **incluir administradores**. Não tenho acesso de admin.

Instruções [(link)](https://cityofaustin.github.io/ctm-dev-workflow/protected-branches.html):

![image](https://user-images.githubusercontent.com/8339493/110250189-ce4e0000-7f58-11eb-94ed-f2eea05b1148.png)

**Comment by petcompufrgs** [comment]
Feito.

**Comment by petcompufrgs** [comment]
Feito.
