### ISSUE TITLE
Como Vamos Buildar No Windows

### ISSUE THREAD

**Issue by brunoczim** [petcomputacaoufrgs/hidracpp#21]
Estamos tentando buildar o Hidra no windows. Com linkagem dinâmica, não conseguimos, o Ricardo tomou erro de DLL faltando. Vamos tentar buildar seguindo [esse link do Qt](https://wiki.qt.io/Build_Standalone_Qt_Application_for_Windows), com linkagem estática. Porém, é necessário buildar o Qt em si também, isso parece um pouco demais?

Se alguém souber uma forma melhor de buildar, eu agradeceria. Como os membros antigos do PET faziam?

**Comment by felipeal** [comment]
Oi @brunoczim, era isso mesmo, não sei de uma forma prática de gerar um executável sem ser buildando o Qt static do zero...

Acredito ser essa página: https://wiki.qt.io/Building_a_static_Qt_for_Windows_using_MinGW

Daí no Qt Creator tem que apontar pra esse Qt static pra gerar o binário.

Lembro que era um pouco trabalhoso fazer tudo funcionar, dá pra documentar na Wiki quando conseguirem.

O .exe vai ficar com aproximadamente 20 MB, sugiro baixar o UPX e usar `upx -9 hidra.exe` pra comprimir pra 5 MB.

Daí seria fazer um Release do `Hidra_vX.Y.Z.zip` no GitHub com esses arquivos:
```
hidra.exe
Hidra_ExemplosNeander.ned
Hidra_GuiaRapido.pdf
Hidra_Referencia.pdf
LICENSE.txt
```
O GitHub exige uma tag de versão do git apontando pro commit do release se não me engano.
