### ISSUE TITLE
Janela fica branca ao clicar em um link do "Sobre"

### ISSUE THREAD

**Issue by igorcmoura** [petcomputacaoufrgs/hidracpp#9]
Quando clico em um dos dois links na janela "Sobre", eles não abrem em lugar nenhum e a janela fica em branco. (Vide imagens)
![2016-09-08 23-01-44](https://cloud.githubusercontent.com/assets/8890509/18373393/150b704c-761a-11e6-90af-54464d646011.png)
![2016-09-08 23-02-10](https://cloud.githubusercontent.com/assets/8890509/18373344/c508b5aa-7619-11e6-8d17-b1b55f39dabe.png)

**Comment by felipeal** [comment]
Resolvido para o release v1.0.1, habilitando "Open external links"
